sudo: required
language: python
python:
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev

install:
  - |
    travis_wait travis_retry pip install scipy numpy
    make test-dependencies
    # eventually get rid of this when on codecov:
    pip install coveralls
    pip install -e .

script:
  - make test

after_success:
  - |
    # TODO: switch to codecov
    coveralls || echo "Coveralls upload failed"
