sudo: required
language: python

before_install:
  - ./build_tools/travis/before_install.sh

env:
  global:
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4
  matrix:
   - DISTRIB="conda" PYTHON_VERSION="3.6"
   - DISTRIB="conda" PYTHON_VERSION="3.7"

install:
  - ./build_tools/travis/install.sh

script:
  - conda activate testenv || echo "testenv already active"
  - make test

after_success: ./build_tools/travis/after_success.sh
